name: Bundle Release

on:
  # Run when a release is published
  release:
    types:
      - published

jobs:
  bundle-and-release:
    name: Bundle and release library
    runs-on: ubuntu-latest
    permissions:
      contents: write # Used to upload the bundled library
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Roc
        uses: roc-lang/setup-roc@30ff82b396cbeb36a662a18f5c652773efb43e72
        with:
          version: nightly-new-compiler
      - name: Bundle and release the library
        uses: hasnep/bundle-roc-library@main
        with:
          library: package/main.roc # Path to the library's entrypoint
          token: ${{ github.token }}