name: Check and Test Package
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-test:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Roc
        uses: hasnep/setup-roc@v0.5.0
        with:
          roc-version: 0.0.0-alpha2-rolling
      - name: Roc check main.roc
        run: roc check package/main.roc
      - name: Roc test main.roc
        run: roc test package/main.roc
    #   - name: Run roc check on examples
    #     run: for roc_file in ./examples/*.roc; do roc check $roc_file; done